version: "3.7"

services:
  my-app:
    container_name: my-shop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - "8083:80"
    environment:
      - CHOKIDAR_USEPOLLING=true

# networks:
#   pos-g2:
#     driver: bridge