version: "3.7"

services:
  my-app:
    container_name: my-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - "8081:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
